services:
  autovol:
    build:
      context: .
      dockerfile: Dockerfile
    image: autovol-app 
    container_name: autovol_container
    
    stdin_open: true # Equivalent to docker run -i
    tty: true        # Equivalent to docker run -t
    
    env_file:
      - .env

    volumes:
      - "./sample_dumps/test_dump.mem:/mnt/dump.mem:ro" 
      - "./gcloud_keys/vertex_key.json:/gcloud_key/vertex_key.json:ro"
      - "./autovol_output:/app/reports"

    # This is an exact copy-pasted scenario from the original Ramnit Lab exertise from CyberDefenders
    # https://cyberdefenders.org/blueteam-ctf-challenges/ramnit/
    command: [
      "/mnt/dump.mem",
      "--context",
      "Our intrusion detection system has alerted us to suspicious behavior on a workstation, pointing to a likely malware intrusion. A memory dump of this system has been taken for analysis. Your task is to analyze this dump, trace the malware’s actions, and report key findings."
    ]
