services:
  autovol:
    build:
      context: .
      dockerfile: Dockerfile
    image: autovol-app 
    container_name: autovol_container
    
    stdin_open: true # Equivalent to docker run -i
    tty: true        # Equivalent to docker run -t

    volumes:
      - "./sample_dumps/test_dump.mem:/mnt/dump.mem:ro" 
      - "./gcloud_keys/vertex_key.json:/gcloud_key/vertex_key.json:ro"
      - "./autovol_output:/app/reports"

    command: [
      "/mnt/dump.mem",
      "--context",
      "This is a test of the help command. Just testing the help command for showing info about plugins.",
    ]
