services:
  autovol:
    build:
      context: .
      dockerfile: Dockerfile
    image: autovol-app 
    container_name: autovol_container
    
    stdin_open: true # Equivalent to docker run -i
    tty: true        # Equivalent to docker run -t

    volumes:
      - "./sample_dumps/test_dump.mem:/mnt/dump.mem:ro" 
      - "./gcloud_keys/vertex_key.json:/gcloud_key/vertex_key.json:ro"
      - "./autovol_output:/app/reports"

    command: [
      "/mnt/dump.mem",
      "--context",
      "A user's computer crashed unexpectedly and we have obtained a memory dump for analysis. The user reports seeing a black window pop up with something being executed just before the crash. At the time of the crash, the user was working on a drawing application. Our objective is to recover important files from the system and understand what caused the crash. Please conduct a thorough analysis focusing on: 1) Identifying the process associated with the black window that appeared before the crash, 2) Locating and extracting any important user files, particularly those related to drawing or creative work, 3) Determining what was being executed in the suspicious black window, 4) Finding any forensic artifacts that could explain the crash. Note: This investigation should uncover 3 specific flags hidden within the memory dump. Please document all findings, recovered files, and the 3 flags in your analysis.",
    ]
