services:
  autovol:
    build:
      context: .
      dockerfile: Dockerfile
    image: autovol-app 
    container_name: autovol_container
    
    stdin_open: true # Equivalent to docker run -i
    tty: true        # Equivalent to docker run -t

    volumes:
      - "./sample_dumps/test_dump.mem:/mnt/dump.mem:ro" 
      - "./gcloud_keys/vertex_key.json:/gcloud_key/vertex_key.json:ro"
      - "./autovol_output:/app/reports"

    command: [
      "/mnt/dump.mem",
      "--context",
      "You're helping me test the image viewing tool. List the files in the workspace and view the iamge in it."
#      "A sister's computer crashed and we have this memory dump. She was trying to draw something when a black window popped up and executed something, then the system crashed. Need to recover important files from the memory dump. This appears to be a forensic challenge with 3 flags to find.",
    ]
