services:
  autovol:
    build:
      context: .
      dockerfile: Dockerfile
    image: autovol-app 
    container_name: autovol_container
    
    stdin_open: true # Equivalent to docker run -i
    tty: true        # Equivalent to docker run -t
    
    env_file:
      - .env

    volumes:
      - "./sample_dumps/test_dump.mem:/mnt/dump.mem:ro" 
      - "./gcloud_keys/vertex_key.json:/gcloud_key/vertex_key.json:ro"
      - "./autovol_output:/app/reports"

    command: [
      "/mnt/dump.mem",
      "--context",
      "You are analyzing a memory dump from a computer that crashed unexpectedly. According to the user (who mentioned it was their sister's computer), they witnessed a black command window appear with something being executed shortly before the crash occurred. At the time of the incident, the user was actively drawing something on the computer. 

      Your objectives are to:
      1) Identify what was running in the black window that appeared before the crash
      2) Recover any important files from the system, particularly any that the user might consider valuable
      3) Investigate what the user was drawing at the time of the crash
      4) Determine if there are any compressed/archived files that might contain important data
      5) Look for any user credentials or authentication artifacts that might be relevant

      This is a CTF-style investigation with 3 specific flags hidden within the memory dump that need to be discovered. Each flag follows the format: flag{...}

      Please conduct a systematic analysis starting with basic system profiling, then examine running processes, and investigate any suspicious or notable findings. Document your analysis process, findings, and any flags discovered."
    ]
